In [19]:
import json
from utils.text_processing import TextProcessing

t = TextProcessing()
#Reading data
queries = []
with open('./data/anonymous labeled conversations.json',) as f:
    for line in f:
        load_line = json.loads(line)
        load_line['processed_message'] = t.process_text(load_line['original_message'])
        queries.append(load_line)
queries

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


[{'original_message': '<p>I was unable to complete an eBay transaction with my card. I tried twice. First failure so far!</p>',
  'tag1': 'APP - Outage',
  'tag2': None,
  'tag3': None,
  'processed_message': 'i was unable to complete an ebay transaction with my card i tried twice first failure so far'},
 {'original_message': "<p>Hi, I still haven't received my mondo card and it was expected on Monday.  I was told to contact you by the end of the week if it had not arrived, thanks!</p>",
  'tag1': 'CARD - Not Arrived',
  'tag2': None,
  'tag3': None,
  'processed_message': 'i still havent received my mondo card and it was expected on monday i was told to contact you by the end of the week if it had not arrived thanks'},
 {'original_message': "<p>Hey, I'm liking the new app design but ever since this last update, I have to re-sign into the app (via the email magic link) practically every time I launch it. It's getting a little inconvenient!</p>",
  'tag1': 'APP - iOS Bug (known)',
  'ta

In [32]:
import operator
freq={}
for i in queries:
    freq[i['tag1']] = freq.get(i['tag1'],0) + 1

sorted(freq.items(),key=operator.itemgetter(1),reverse=True)

t = []
for i in range(len(queries)):
    value = queries[i]['tag1']
    t.append(value)
set(t)
s = sorted(freq.items(),key=operator.itemgetter(1),reverse=True)
[x[0]:i for i, x in enumerate(s)]

SyntaxError: invalid syntax (2560770191.py, line 14)

In [91]:
from utils.text_processing import TextProcessing

In [92]:
t = TextProcessing()
q = "<p>Hey 👋🏼</p>\n\n<p>I got a refund from bet365 yesterday but my balance is still showing £1.33. </p>\n\n<p>Do you know when this will be updated? I'm getting hungry 😋.</p>"
#print(q)
print(t.process_text(q))

i got a refund from bet365 yesterday but my balance is still showing £133 do you know when this will be updated im getting hungry


In [98]:
text=[]
label=[]
df_np = df.to_numpy()
target_label = df.columns[5:]
for i in range(len(df)):
    text.append(df_np[i][4])
    label.append(df_np[i][5:])
    

In [99]:
target_label = df.columns[5:]
target_label

Index(['APP - Outage', 'APP - Unrecognized Transaction',
       'APP - iOS Bug (known)', 'CARD - Not Arrived', 'DECLINE - Contactless',
       'KYC - limit driven', 'ONBOARDING - £100 amount', 'PAYMENT - REFUND',
       'PIN - sent', 'TOP UP - Bank transfer', 'TRAVEL - FX rates',
       'TRAVEL - TfL transaction query'],
      dtype='object')

In [83]:


buffer_size=100
batch_size = 2
seed = 42
validation_split = 0.2

tf_text = tf.convert_to_tensor(text)
tf_label = tf.convert_to_tensor(label)

tf_data = tf.data.Dataset.from_tensor_slices((tf_text,tf_label))
tf_data = tf_data.shuffle(buffer_size)
tf_data = tf_data.batch(batch_size)

In [80]:
for z in tf_data:
    print(z)

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i was unable to complete an ebay transaction with my card i tried twice first failure so far',
       b'i still havent received my mondo card and it was expected on monday i was told to contact you by the end of the week if it had not arrived thanks'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'im liking the new app design but ever since this last update i have to resign into the app via the email magic link practically every time i launch it its getting a little inconvenient',
       b'how come i can not top up more than \xc2\xa3100'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=


(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'guys i just tapped in at west wickham i am on my way to cannon street it shows 970 on my mondo card something is wrong looks like they have charged me full amount yesterday i travelled from cannon street to lewisham then tapped out at lewisham tapped in again due to some train delayschaos and tapped out in westwickham looks like something has gone wrong and tfl has charged me a full amount please can you help thanks',
       b'whats wrong'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'guys i know it is early in the morning but have been trying to top up for a couple of hours now jet lagged but the top up page seems to hang',
       b'there ive forgotten my pin could you send me a reminder please thx'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtyp

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'there i have a small problem i forgot my pin and no longer have the phone with which i accepted the pin text message',
       b'need pin reminder how do i obtain'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'just a quickie been on hols and never managed to use my card as forgot my pin ampdelayed sms about it can you resetresend thanks mike',
       b'hello can i use my card abroad'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'could you send me a pin reminder please',
       b'have you really only just dispatched my card it said it should get to me on friday and im going abroad

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'can you please send me the pin',
       b'i have 5 transaction for same price and at same location its appears as \xc2\xa35 have spent 5 times at same place which equals to \xc2\xa325 although i do remember buying coffee there however i couldnt not buy it 5 times'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i spoke to tfl and they told me that they have refund \xc2\xa3730 back to this card last week monday but the refund havent got back into the card',
       b'i didnt get chance to change my monzo pin to something id remember and since getting a new phone ive lost the text where it told me please could you helpthank you krista'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'what do i need to do so i can top up again more regularly',
       b'i recently applied for a replacement card but i havent received it at all is there a way where it can get a new one sent out'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'ive had to reset my phone and just installed everything and have just realised ive forgotten my pin how can i reset this thanks',
       b'i can only ever top up small amounts usually its around \xc2\xa3150 but id like to put more in worse yet today its only allowing me to add \xc2\xa330'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'wait did that send',
       b'hello i want to use my belgian card from ing to top up my account how do i do it because it doesnt recognise my card en number'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i tried to top up my oyster \xc2\xa320 yesterday but the transaction never completed coz i forgot to touch my oyster card on the yellow reader after my monzo card payment however the payment has still been taken out of my monzo account according to the app',
       b'would it be possible to verify my account please'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'trying to t

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'both my wife and i have just tried to use our cards in the local tesco and they were both declined even through there is money on both but strangely the declined transaction is not showing up on my monzo transactions is there anything wrong this morning',
       b'there can i check if i put money on today will it go on tonight or only after the weekend im heading to amsterdam and wanted to use the card there it had slipped my mind to do it before today'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'now youve renamed and launched is there any chance of getting a new shiny card',
       b'would you somehow be able to send me a pin im having problems with changing it thank you x'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
ar

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'my card just declined do you know why im going to thailand today and i need it to work',
       b'my mondo card was declined couple of times and i couldnt withdraw cash'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'im not sure this should show up in the spending its just a card check which has now been refunded',
       b'i verified my id and its still not letting me top up'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'hello i set up a standing order into my mondo account funds where taken for it on thursday last week but the balance still hasnt gone onto my mondo 

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i have just had a refund from waitrose but it hasnt come up on my statement',
       b'guys been over a week and no card whats next steps'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'my card has failed the last three times ive tried to use it contactless chip and pin and at an atm',
       b'please reset my pin number'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'ive just activated my card through the app but the text with my pin hasnt come through',
       b'i transferred \xc2\xa3200 to monzo two days ago and it hasnt shown up in my account but has been debited from my

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'contact less isnt working in manchester today chip and pin still works fine just wondering if theres a known issue today',
       b'good eveningi have forgotten my pin could i please get some support'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'there i have forgotten my pin number',
       b'there i have a \xc2\xa325 charge from amazon which i dont recognise and cant reconcile with my order record online not sure what to do and appreciate your help thanks'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'can you let me know whats going on with the bug that stops peopl

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'guys i was kicked out of the app for two times the last two days i had torequest an email and log in via the email link again this is particularly inconvenient for me as im currently on a road trip in the usa is that a known problem or is there anything i can do to avoid this behaviour',
       b'i didnt make this transaction'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'for the first usage of my card i dont know where i can see the pin code can someone help please',
       b'im still waiting for my monzo card is it possible to track it'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, nump

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i just received an empty letter without the card',
       b'in order to have a regular payment into my account or rather card as it is right now do i simply use the card number thanks'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i just tried to pay with my card with contact less but just got card not accepted do i need to activate or pay with my pin for the first time',
       b'is there are problem with my second monzo card being used for contactless travel i evidently need some assistance from your end because apparently tfl can not see these recurring issuesearly in this month i was charged a duplicate days travel off my monzo card to value of \xc2\xa3930after much back and forth and screenshots of my tfl statements a monzo cs operative refunde

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'guys quick question is there a reason i can only top up a maximum of \xc2\xa340',
       b'guysjust tried to pay for a train ticket and my card was declined any thoughts'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'having a bit of an issue where i keep getting logged out of the monzo app and have to keep sending the email each time to log in',
       b'my card was declined twice today i didnt get a notification and was just wondering if there were any logs available to check if my card will work next time thanks'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'how do

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'there i have forgotten my pin what can i do',
       b'i dont recognise this transaction by tfl i think this is the second time i have been over charged'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'hitheres a new credit on my account goodwill gesture do you know where this has come fromthanks',
       b'activated my card today still havent got my pin'], dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'hello could you please confirm the dates of the tfl transactions',
       b'i havnt travelled today there should be no tfl payment from my card'],
      dtype=object)>, <tf.Tens

(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'hiim trying to top up but says ive reached my top up limit is there any way i can get a higher limit no limit please',
       b'ive forgotten my pin could you please help me out thanks'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'there ive forgotten my pin how do i get it sent to me again besttristan',
       b'i keep getting logged out a lot recently invalid token error ios 10'],
      dtype=object)>, <tf.Tensor: shape=(2, 12), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>)
(<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'i cant use my card i forgot my number and it is been blocked',
       b'hello there i dont recognise this withdrawal because im in london and t

In [85]:
for batch in tf_data.take(4):
  print([arr.numpy() for arr in batch])

[array([b'any reason the totals dont add up in my spending section appear to be rounded down',
       b'can you please increase my topup limit i \xe2\x80\x99 m in expensive norway\xe2\x80\xa6'],
      dtype=object), array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int32)]
[array([b'folks had some issues with chip amp pin at sainsburys earlier tried the card on a couple of terminals and was declined at both has worked absolutely fine before so wanted to flag have you heard of anyone else having similar issues',
       b'there ive made a purchase in coop yesterday and later on refund for a item ive done all the process directly at the till and the clerk said its refunded however after a day i still see no records in my monzo dashboard does that mean the refund was failed what should i do next thanks'],
      dtype=object), array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int32)]
[array([b'i do

In [1]:
from transformer import Transformer
t = Transformer()
x_train, x_val, x_test, y_train, y_val, y_test = t.train_val_test_split()

2021-08-08 16:19:53.706520: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-08 16:19:53.706618: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
from model import bert

In [3]:
import tensorflow as tf
text_test = ['this is such an amazing movie!']
multiclass_model = bert.build_bert_model()
bert_raw_result = multiclass_model(tf.constant(text_test))
print(bert_raw_result)

2021-08-08 16:20:11.106745: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-08 16:20:11.106880: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-08 16:20:11.106951: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (9574da91b317): /proc/driver/nvidia/version does not exist
2021-08-08 16:20:11.107631: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-08-08 16:20:13.182420: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR O

tf.Tensor(
[[ 0.42298844  0.12301115 -0.6991501  -0.8771557   1.5210739  -0.20794906
   0.74350613  0.95880765 -0.30750203 -0.5604355   0.7436906   0.9487898 ]], shape=(1, 12), dtype=float32)


In [4]:
loss = tf.keras.losses.CategoricalCrossentropy()
metrics = tf.metrics.Accuracy()

epochs = 5
steps_per_epoch = len(x_train)
num_train_steps = steps_per_epoch * epochs
num_warmup_steps = int(0.1*num_train_steps)

init_lr = 3e-5
optimizer = tf.keras.optimizers.Adam(learning_rate=init_lr)

#optimizer = keras.optimization.create_optimizer(init_lr=init_lr,
#                                          num_train_steps=num_train_steps,
#                                          num_warmup_steps=num_warmup_steps,
#                                          optimizer_type='adamw')

In [5]:
multiclass_model.compile(optimizer=optimizer,
                         loss=loss,
                         metrics=metrics)

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=3)

history = multiclass_model.fit(x = tf.convert_to_tensor(x_train), y = tf.convert_to_tensor(y_train) , validation_data=(x_val, y_val), epochs=5, callbacks = [early_stopping])

Epoch 1/5


In [1]:
history

history


In [11]:
import os
os.getcwd()

'/app'

In [12]:
import pickle

In [26]:
import math
2* math.exp(-5)

0.013475893998170934

In [17]:
pip install matplotlib


     |████████████████████████████████| 10.3 MB 10.5 MB/s eta 0:00:01
     |████████████████████████████████| 3.0 MB 14.7 MB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 7.4 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [25]:
max_len = []
for i in range(len(queries)):
    q_len = len(queries[i]['original_message'])
    max_len.append(q_len)
max_len

[102,
 161,
 204,
 48,
 38,
 115,
 10,
 170,
 12,
 340,
 260,
 162,
 152,
 154,
 222,
 76,
 123,
 171,
 205,
 63,
 33,
 105,
 173,
 69,
 199,
 103,
 252,
 208,
 97,
 149,
 127,
 139,
 276,
 81,
 147,
 155,
 41,
 123,
 184,
 250,
 150,
 194,
 76,
 349,
 45,
 45,
 91,
 147,
 79,
 190,
 56,
 47,
 93,
 75,
 218,
 230,
 250,
 17,
 67,
 93,
 40,
 61,
 98,
 118,
 109,
 121,
 373,
 80,
 97,
 236,
 304,
 123,
 79,
 291,
 132,
 458,
 156,
 67,
 138,
 12,
 54,
 312,
 120,
 160,
 161,
 67,
 221,
 189,
 206,
 66,
 76,
 75,
 81,
 114,
 91,
 185,
 157,
 305,
 150,
 97,
 121,
 97,
 189,
 12,
 84,
 184,
 84,
 244,
 80,
 167,
 158,
 90,
 41,
 31,
 25,
 50,
 26,
 150,
 91,
 194,
 205,
 109,
 167,
 156,
 122,
 117,
 108,
 82,
 134,
 96,
 37,
 74,
 103,
 76,
 142,
 63,
 94,
 68,
 114,
 58,
 76,
 41,
 105,
 22,
 14,
 56,
 114,
 65,
 54,
 64,
 70,
 128,
 27,
 49,
 54,
 54,
 108,
 66,
 132,
 50,
 56,
 59,
 544,
 86,
 88,
 68,
 176,
 70,
 93,
 112,
 10,
 153,
 77,
 91,
 232,
 154,
 193,
 14,
 253,
 110,
 29,
 

In [31]:
import numpy as np
y_true = np.array([[1,0,0],[0,1,0]])
y_pred = np.array([[1,0,0],[1,0,0]])


In [8]:
from sklearn.metrics import accuracy_score
y_true = ['a','b']
y_pred = ['a','a']
accuracy_score(y_true, y_pred)

0.5

In [34]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_true, y_pred)

ValueError: multilabel-indicator is not supported

In [2]:
from transformer import Transformer
t = Transformer()
x_train, x_val, x_test, y_train, y_val, y_test = t.train_val_test_split()

In [6]:
import tensorflow as tf
tf.convert_to_tensor(x_train[0:2])

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b'ive forgotten my pin',
       b'on 30th october i topped by my card with \xc2\xa3100 but the money never appeared please help'],
      dtype=object)>

In [1]:
import app
history, mc_model = app.model_fit()

2021-08-09 13:10:30.746553: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-09 13:10:30.746650: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
2021-08-09 13:10:41.725956: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-08-09 13:10:41.726044: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-09 13:10:41.726077: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (9574da91b31

IndexError: list index out of range

In [ ]:

import operator
freq={}
for i in queries:
    freq[i['tag1']] = freq.get(i['tag1'],0) + 1

In [ ]:
from matplotlib import pyplot as plt
plt.xticks(rotation=90)
plt.title("tag1 frequency count")
plt.ylabel("frequency")
plt.bar(freq.keys(), freq.values(), width=.5, color='g')